/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pets.amok;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class OrganicTest {
    
    private Organic pet;

    @BeforeEach
    public void newPet() {
        pet = new Organic("Rosie", "Organic Cat");
    }

    @Test
    public void shouldGetNameAndType() {
        assertEquals("Rosie", pet.getPetName());
        assertEquals("Organic Cat", pet.getDescription());
    }

    @Test
    public void testDefaultValues() {
        assertEquals(50, pet.getHunger());
        assertEquals(50, pet.getThirst());
        assertEquals(50, pet.getBoredom());
        assertEquals(0, pet.getWaste());
    }

    @Test
    public void shouldTick() {
        pet.tick();
        assertEquals(51, pet.getHunger());
        assertEquals(51, pet.getThirst());
        assertEquals(51, pet.getBoredom());
        assertEquals(1, pet.getWaste());
    }

}
